### ISSUE TITLE
Priorities + 2.7

### ISSUE THREAD

**Issue by inverse** [evispa/NercuryCodeIgniterBundle#7]
It seems like the Symfony router kicks in before this bundles listener tries to resolve things and thus fails :(. Also the service needs to be made public. On 2.7 this is.

**Comment by inverse** [comment]
Master is working, just not the tagged version. Perhaps a new release?

**Comment by dariuszz123** [comment]
1.3.0-beta rolled out :)

**Comment by inverse** [comment]
Awesome :+1: Thanks!
